import matplotlib.pyplot as plt
import pandas as pd

# Load the data generated by your C++ RK4 solver
df = pd.read_csv('mirage_data.csv')

plt.figure(figsize=(10, 5))
plt.plot(df['x'], df['y'], label='Light Ray Path', color='orange', linewidth=2)

# Styling to show the "Mirage" effect
plt.axhline(0, color='black', lw=2) # The Ground
plt.fill_between(df['x'], -0.5, 0, color='gray', alpha=0.3) # Road/Ground surface

plt.title('Light Ray Trajectory (Mirage Model)')
plt.xlabel('Horizontal Distance (x)')
plt.ylabel('Height (y)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()
